# Homebrew info

APP_TITLE       := MultiUpdater
APP_DESCRIPTION := Updater for FIRM payloads, CIAs, and other files.
APP_AUTHOR      := LiquidFenrir

ICON            := resources/icon.png

# CIA info

PRODUCT_CODE := CTR-P-ULTI
UNIQUE_ID    := 0xd5c49

BANNER_AUDIO := resources/audio.wav
BANNER_IMAGE := resources/banner.png

# Directories

BINNAME := MultiUpdater
BINDIR  := out
BUILD   := build
SOURCES := source source/minizip

# Build info

LIBRARIES := ctru m z jansson
